title: IotManPlatform
description: IotManPlatform是一个开放免费的物联平台。
show_downloads: true
git_branch: master
logo_url:
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
